### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by itay-grudev** [derEisele/G213Colors#14]
Add a sponsor URL or sign up for GitHub Sponsors.

https://github.com/sponsors

https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

I would like to support your project.

**Comment by dereisele** [comment]
Thanks a lot for your offer of support! Since receiving money for a project always comes with the moral duty of actively working on it, I cannot receive it. I have just no time or interest to add new features or fix bugs on a regular basis.

That doesn't me that you can't fork this repo and send improvements as pull request.

I hope you understand

**Comment by itay-grudev** [comment]
I completely understand. Have a great evening.
